//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" or "Add Foundational Module" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-270-Creating%20a%20Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.ChkAddrModule.Interface.Constants
{
    /// <summary>
    /// Constants for command names.
    /// </summary>
    public class CommandNames : ACOT.Infrastructure.Interface.Constants.CommandNames
    {
        public const string CheckAll = "CheckAll";
        public const string ManualEdit = "ManualEdit";
    }
}
