//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" or "Add Foundational Module" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-270-Creating%20a%20Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.ChkAddrModule.Interface.Constants
{
    /// <summary>
    /// Constants for event topic names.
    /// </summary>
    public class EventTopicNames : ACOT.Infrastructure.Interface.Constants.EventTopicNames
    {
        public const string ChoiceSubDivision = "event://ChoiceSubDivision";

        public const string CheckAllBtnIsPressed = "event://CheckAllBtnIsPressed";

        public const string ManualEditBtnIsPressed = "event://ManualEditBtnIsPressed";

        public const string MainViewShow = "event://MainLayoutViewShow";

        public const string EditorViewShow = "event://EditorLayoutViewShow";

        public const string AddrElementsSelectionViewShow = "event://AddrElementsSelectionViewShow";

        public const string DatasetUpdate = "event://DataSetUpdate";

        public const string SearchName = "event://SearchName";

        public const string CurrentAddressInfoUpdate = "event://CurrentAddressInfoUpdate";

        public const string EditorViewClose = "event://OnEditorViewClose";

        
    }
}
