//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// The WindowWorkspace class provides an extension to the builtin CAB WindowWorkspace 
// by allowing better customization of the form: Accept and Cancel button and FormBorderStyle
// 
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/03-01-010-How_to_Create_Smart_Client_Solutions.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using System.Windows.Forms;

namespace ChkAddr.Infrastructure.Library.UI
{
    public class WindowWorkspace : Microsoft.Practices.CompositeUI.WinForms.WindowWorkspace
    {
        IWin32Window _owner;
        
        public delegate EventHandler Closed(object sender, EventArgs e);

        public delegate System.Windows.Forms.FormClosingEventHandler Closing(object sender, FormClosingEventArgs e);

        public event EventHandler OnKeyDown;

        public event EventHandler OnClosed;

        public event System.Windows.Forms.FormClosingEventHandler OnClosing;

        public WindowWorkspace()
        {
        }

        public WindowWorkspace(IWin32Window owner)
            : base(owner)
        {
            _owner = owner;
        }

        protected override void OnShow(Control smartPart, Microsoft.Practices.CompositeUI.WinForms.WindowSmartPartInfo smartPartInfo)
        {
            GetOrCreateForm(smartPart);
            OnApplySmartPartInfo(smartPart, smartPartInfo);
            base.OnShow(smartPart, smartPartInfo);
        }

        protected override void OnClose(Control smartPart)
        {
            Form host = Windows[smartPart];
            host.Hide();
            base.OnClose(smartPart);
        }

        protected override void OnApplySmartPartInfo(Control smartPart, Microsoft.Practices.CompositeUI.WinForms.WindowSmartPartInfo smartPartInfo)
        {
            base.OnApplySmartPartInfo(smartPart, smartPartInfo);
            if (smartPartInfo is WindowSmartPartInfo)
            {
                WindowSmartPartInfo spi = (WindowSmartPartInfo)smartPartInfo;
                if (spi.Keys.ContainsKey(WindowWorkspaceSetting.AcceptButton))
                    Windows[smartPart].AcceptButton = (IButtonControl)spi.Keys[WindowWorkspaceSetting.AcceptButton];
                if (spi.Keys.ContainsKey(WindowWorkspaceSetting.CancelButton))
                    Windows[smartPart].CancelButton = (IButtonControl)spi.Keys[WindowWorkspaceSetting.CancelButton];
                if (spi.Keys.ContainsKey(WindowWorkspaceSetting.FormBorderStyle))
                    Windows[smartPart].FormBorderStyle = (FormBorderStyle)spi.Keys[WindowWorkspaceSetting.FormBorderStyle];
                if (spi.Keys.ContainsKey(WindowWorkspaceSetting.AutoSize))
                    Windows[smartPart].AutoSize = (bool)spi.Keys[WindowWorkspaceSetting.AutoSize];
                if (spi.Keys.ContainsKey(WindowWorkspaceSetting.FormShowIcon))
                    Windows[smartPart].ShowIcon = (bool)spi.Keys[WindowWorkspaceSetting.FormShowIcon];
                if (spi.Keys.ContainsKey(WindowWorkspaceSetting.FormShowInTaskbar))
                    Windows[smartPart].ShowInTaskbar = (bool)spi.Keys[WindowWorkspaceSetting.FormShowInTaskbar];
                if (spi.Keys.ContainsKey(WindowWorkspaceSetting.StartPosition))
                    Windows[smartPart].StartPosition = (FormStartPosition)spi.Keys[WindowWorkspaceSetting.StartPosition];
                if (spi.Keys.ContainsKey(WindowWorkspaceSetting.KeyPreview))
                    Windows[smartPart].KeyPreview = (bool)spi.Keys[WindowWorkspaceSetting.KeyPreview];
                if (spi.Keys.ContainsKey(WindowWorkspaceSetting.Dock))
                    Windows[smartPart].Dock = (DockStyle)spi.Keys[WindowWorkspaceSetting.Dock];
                if (spi.Keys.ContainsKey(WindowWorkspaceSetting.KeyDown))
                    Windows[smartPart].KeyDown += (KeyEventHandler)spi.Keys[WindowWorkspaceSetting.KeyDown];
            }
        }

        protected new Form GetOrCreateForm(Control control)
        {
            bool resizeRequired = !Windows.ContainsKey(control);
            Form form = base.GetOrCreateForm(control);
            form.ShowInTaskbar = (_owner == null);
            if (resizeRequired)
                form.ClientSize = control.Size;
            form.Closed += new EventHandler(Form_Closed);
            form.FormClosing += new System.Windows.Forms.FormClosingEventHandler(Form_Closing);
            return form;
        }

        protected void Form_Closed(object sender, EventArgs e)
        {
            if (OnClosed != null)
                OnClosed(sender, e);
        }

        protected void Form_Closing(object sender, FormClosingEventArgs e)
        {
            if (OnClosing != null)
                OnClosing(sender, e);
        }
    }
}
