//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// A presenter calls methods of a view to update the information that the view displays. 
// The view exposes its methods through an interface definition, and the presenter contains
// a reference to the view interface. This allows you to test the presenter with different 
// implementations of a view (for example, a mock view).
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Windows.Forms;
using ACOT.ChkAddrModule.Constants;
using ACOT.ChkAddrModule.Interface.BusinessEntities;
using ACOT.Services.WorkersService;
using Microsoft.Practices.CompositeUI.EventBroker;
using Microsoft.Practices.ObjectBuilder;
using Microsoft.Practices.CompositeUI;
using ACOT.Infrastructure.Interface;
using ACOT.ChkAddrModule.Interface.Services;

namespace ACOT.ChkAddrModule.Views.IndexerView
{
    public partial class IndexerViewPresenter : Presenter<IndexerView>
    {
        private IMdbService _mdbService;

        /// <summary>
        /// This method is a placeholder that will be called by the view when it has been loaded.
        /// </summary>
        public override void OnViewReady()
        {
            View.Progress.Maximum = 8;
            View.SetPosition();
            //IndexingRun();
            base.OnViewReady();
        }


        /// <summary>
        /// Close the view
        /// </summary>
        public override void OnCloseView()
        {
            base.CloseView();
        }

        //[EventSubscription(EventTopicNames.ChkAddrModuleClose, ThreadOption.UserInterface)]
        //public void OnChkModuleClose(object sender, EventArgs e)
        //{
        //    View.ParentForm.Close();
        //}

        //[EventSubscription(EventTopicNames.IndexingRun, ThreadOption.UserInterface)]
        //public void IndexingRun(object sender, EventArgs<IIndexerView> e)
        //public void IndexingRun()
        //{
        //    _mdbService = WorkItem.Services.Get<IMdbService>();
        //    _mdbService.IndexingRun(View);
        //}

        internal void UserCloseForm()
        {
            CloseView();
            if (ChkModuleClose != null)
                ChkModuleClose(this, EventArgs.Empty);
        }

        [EventPublication(EventTopicNames.ChkAddrModuleClose, PublicationScope.WorkItem)]
        public event EventHandler ChkModuleClose;
    }
}

