
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.ChkAddrModule.Views.EditorView
{
    partial class EditorView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private ACOT.ChkAddrModule.Views.EditorView.EditorViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EditorView));
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this._saveAndCloseBtn = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this._closeBtn = new System.Windows.Forms.ToolStripButton();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label17 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label19 = new System.Windows.Forms.Label();
            this.label18 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this._UlicaErrorPicture = new System.Windows.Forms.PictureBox();
            this._NaspunktErrorPicture = new System.Windows.Forms.PictureBox();
            this._GorodErrorPicture = new System.Windows.Forms.PictureBox();
            this._RaionErrorPicture = new System.Windows.Forms.PictureBox();
            this.label9 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this._kvartTb = new System.Windows.Forms.TextBox();
            this.label11 = new System.Windows.Forms.Label();
            this._korpTb = new System.Windows.Forms.TextBox();
            this.label10 = new System.Windows.Forms.Label();
            this._domTb = new System.Windows.Forms.TextBox();
            this._ulicaSelectBtn = new System.Windows.Forms.Button();
            this._ulicaTb = new System.Windows.Forms.TextBox();
            this._naspunktSelectBtn = new System.Windows.Forms.Button();
            this._naspunktTb = new System.Windows.Forms.TextBox();
            this._gorodSelectBtn = new System.Windows.Forms.Button();
            this._gorodTb = new System.Windows.Forms.TextBox();
            this._raionSelectBtn = new System.Windows.Forms.Button();
            this._raionTb = new System.Windows.Forms.TextBox();
            this._indexTb = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this._regLabel = new System.Windows.Forms.Label();
            this._kodRegBtn = new System.Windows.Forms.Button();
            this._kodRegTb = new System.Windows.Forms.TextBox();
            this._fullAddrTb = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this._rightWorkspace = new Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace();
            this._termianteBtn = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStrip1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this._UlicaErrorPicture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._NaspunktErrorPicture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._GorodErrorPicture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._RaionErrorPicture)).BeginInit();
            this.SuspendLayout();
            // 
            // toolStrip1
            // 
            this.toolStrip1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.toolStrip1.Font = new System.Drawing.Font("Tahoma", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.toolStrip1.GripStyle = System.Windows.Forms.ToolStripGripStyle.Hidden;
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this._saveAndCloseBtn,
            this.toolStripSeparator1,
            this._closeBtn,
            this.toolStripSeparator2,
            this._termianteBtn});
            this.toolStrip1.Location = new System.Drawing.Point(0, 457);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(1024, 25);
            this.toolStrip1.TabIndex = 27;
            this.toolStrip1.Text = "toolStrip1";
            // 
            // _saveAndCloseBtn
            // 
            this._saveAndCloseBtn.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this._saveAndCloseBtn.Image = ((System.Drawing.Image)(resources.GetObject("_saveAndCloseBtn.Image")));
            this._saveAndCloseBtn.ImageTransparentColor = System.Drawing.Color.Magenta;
            this._saveAndCloseBtn.Name = "_saveAndCloseBtn";
            this._saveAndCloseBtn.Size = new System.Drawing.Size(137, 22);
            this._saveAndCloseBtn.Text = "Сохранить - F10";
            this._saveAndCloseBtn.Click += new System.EventHandler(this._saveAndCloseBtn_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(6, 25);
            // 
            // _closeBtn
            // 
            this._closeBtn.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this._closeBtn.Image = ((System.Drawing.Image)(resources.GetObject("_closeBtn.Image")));
            this._closeBtn.ImageTransparentColor = System.Drawing.Color.Magenta;
            this._closeBtn.Name = "_closeBtn";
            this._closeBtn.Size = new System.Drawing.Size(89, 22);
            this._closeBtn.Text = "Отменить";
            this._closeBtn.Click += new System.EventHandler(this._closeBtn_Click);
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.label17);
            this.groupBox1.Controls.Add(this.label12);
            this.groupBox1.Controls.Add(this.label19);
            this.groupBox1.Controls.Add(this.label18);
            this.groupBox1.Controls.Add(this.label16);
            this.groupBox1.Controls.Add(this.label15);
            this.groupBox1.Controls.Add(this.label14);
            this.groupBox1.Controls.Add(this.label13);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this._UlicaErrorPicture);
            this.groupBox1.Controls.Add(this._NaspunktErrorPicture);
            this.groupBox1.Controls.Add(this._GorodErrorPicture);
            this.groupBox1.Controls.Add(this._RaionErrorPicture);
            this.groupBox1.Controls.Add(this.label9);
            this.groupBox1.Controls.Add(this.label8);
            this.groupBox1.Controls.Add(this.label7);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this._kvartTb);
            this.groupBox1.Controls.Add(this.label11);
            this.groupBox1.Controls.Add(this._korpTb);
            this.groupBox1.Controls.Add(this.label10);
            this.groupBox1.Controls.Add(this._domTb);
            this.groupBox1.Controls.Add(this._ulicaSelectBtn);
            this.groupBox1.Controls.Add(this._ulicaTb);
            this.groupBox1.Controls.Add(this._naspunktSelectBtn);
            this.groupBox1.Controls.Add(this._naspunktTb);
            this.groupBox1.Controls.Add(this._gorodSelectBtn);
            this.groupBox1.Controls.Add(this._gorodTb);
            this.groupBox1.Controls.Add(this._raionSelectBtn);
            this.groupBox1.Controls.Add(this._raionTb);
            this.groupBox1.Controls.Add(this._indexTb);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this._regLabel);
            this.groupBox1.Controls.Add(this._kodRegBtn);
            this.groupBox1.Controls.Add(this._kodRegTb);
            this.groupBox1.Location = new System.Drawing.Point(4, 77);
            this.groupBox1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.groupBox1.Size = new System.Drawing.Size(641, 375);
            this.groupBox1.TabIndex = 32;
            this.groupBox1.TabStop = false;
            // 
            // label17
            // 
            this.label17.AutoSize = true;
            this.label17.Font = new System.Drawing.Font("Trebuchet MS", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label17.ForeColor = System.Drawing.Color.DimGray;
            this.label17.Location = new System.Drawing.Point(511, 47);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(90, 16);
            this.label17.TabIndex = 33;
            this.label17.Text = "Пример: 601551";
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Trebuchet MS", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label12.ForeColor = System.Drawing.Color.DimGray;
            this.label12.Location = new System.Drawing.Point(110, 47);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(170, 16);
            this.label12.TabIndex = 33;
            this.label12.Text = "Пример: 33 - Владимирская обл";
            // 
            // label19
            // 
            this.label19.AutoSize = true;
            this.label19.Font = new System.Drawing.Font("Trebuchet MS", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label19.ForeColor = System.Drawing.Color.DimGray;
            this.label19.Location = new System.Drawing.Point(413, 349);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(72, 16);
            this.label19.TabIndex = 33;
            this.label19.Text = "Пример: 168";
            // 
            // label18
            // 
            this.label18.AutoSize = true;
            this.label18.Font = new System.Drawing.Font("Trebuchet MS", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label18.ForeColor = System.Drawing.Color.DimGray;
            this.label18.Location = new System.Drawing.Point(253, 349);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(60, 16);
            this.label18.TabIndex = 33;
            this.label18.Text = "Пример: 3";
            // 
            // label16
            // 
            this.label16.AutoSize = true;
            this.label16.Font = new System.Drawing.Font("Trebuchet MS", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label16.ForeColor = System.Drawing.Color.DimGray;
            this.label16.Location = new System.Drawing.Point(111, 349);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(66, 16);
            this.label16.TabIndex = 33;
            this.label16.Text = "Пример: 12";
            // 
            // label15
            // 
            this.label15.AutoSize = true;
            this.label15.Font = new System.Drawing.Font("Trebuchet MS", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label15.ForeColor = System.Drawing.Color.DimGray;
            this.label15.Location = new System.Drawing.Point(109, 288);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(100, 16);
            this.label15.TabIndex = 33;
            this.label15.Text = "Пример: 1 Мая ул ";
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("Trebuchet MS", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label14.ForeColor = System.Drawing.Color.DimGray;
            this.label14.Location = new System.Drawing.Point(110, 228);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(117, 16);
            this.label14.TabIndex = 33;
            this.label14.Text = "Пример: Гусевский п ";
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Trebuchet MS", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label13.ForeColor = System.Drawing.Color.DimGray;
            this.label13.Location = new System.Drawing.Point(110, 168);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(156, 16);
            this.label13.TabIndex = 33;
            this.label13.Text = "Пример: Гусь-Хрустальный г ";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Trebuchet MS", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label3.ForeColor = System.Drawing.Color.DimGray;
            this.label3.Location = new System.Drawing.Point(109, 107);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(164, 16);
            this.label3.TabIndex = 33;
            this.label3.Text = "Пример: Гусь-Хрустальный р-н";
            // 
            // _UlicaErrorPicture
            // 
            this._UlicaErrorPicture.Image = ((System.Drawing.Image)(resources.GetObject("_UlicaErrorPicture.Image")));
            this._UlicaErrorPicture.Location = new System.Drawing.Point(585, 258);
            this._UlicaErrorPicture.Name = "_UlicaErrorPicture";
            this._UlicaErrorPicture.Size = new System.Drawing.Size(23, 25);
            this._UlicaErrorPicture.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this._UlicaErrorPicture.TabIndex = 32;
            this._UlicaErrorPicture.TabStop = false;
            // 
            // _NaspunktErrorPicture
            // 
            this._NaspunktErrorPicture.Image = ((System.Drawing.Image)(resources.GetObject("_NaspunktErrorPicture.Image")));
            this._NaspunktErrorPicture.Location = new System.Drawing.Point(584, 198);
            this._NaspunktErrorPicture.Name = "_NaspunktErrorPicture";
            this._NaspunktErrorPicture.Size = new System.Drawing.Size(23, 25);
            this._NaspunktErrorPicture.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this._NaspunktErrorPicture.TabIndex = 32;
            this._NaspunktErrorPicture.TabStop = false;
            // 
            // _GorodErrorPicture
            // 
            this._GorodErrorPicture.Image = ((System.Drawing.Image)(resources.GetObject("_GorodErrorPicture.Image")));
            this._GorodErrorPicture.Location = new System.Drawing.Point(584, 138);
            this._GorodErrorPicture.Name = "_GorodErrorPicture";
            this._GorodErrorPicture.Size = new System.Drawing.Size(23, 25);
            this._GorodErrorPicture.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this._GorodErrorPicture.TabIndex = 32;
            this._GorodErrorPicture.TabStop = false;
            // 
            // _RaionErrorPicture
            // 
            this._RaionErrorPicture.Image = ((System.Drawing.Image)(resources.GetObject("_RaionErrorPicture.Image")));
            this._RaionErrorPicture.Location = new System.Drawing.Point(585, 77);
            this._RaionErrorPicture.Name = "_RaionErrorPicture";
            this._RaionErrorPicture.Size = new System.Drawing.Size(23, 25);
            this._RaionErrorPicture.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this._RaionErrorPicture.TabIndex = 32;
            this._RaionErrorPicture.TabStop = false;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label9.ForeColor = System.Drawing.Color.Navy;
            this.label9.Location = new System.Drawing.Point(60, 324);
            this.label9.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(41, 16);
            this.label9.TabIndex = 31;
            this.label9.Text = "Дом:";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label8.ForeColor = System.Drawing.Color.Navy;
            this.label8.Location = new System.Drawing.Point(49, 263);
            this.label8.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(58, 16);
            this.label8.TabIndex = 30;
            this.label8.Text = "Улица:";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label7.ForeColor = System.Drawing.Color.Navy;
            this.label7.Location = new System.Drawing.Point(19, 203);
            this.label7.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(91, 16);
            this.label7.TabIndex = 29;
            this.label7.Text = "Нас. пункт:";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label6.ForeColor = System.Drawing.Color.Navy;
            this.label6.Location = new System.Drawing.Point(51, 143);
            this.label6.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(56, 16);
            this.label6.TabIndex = 28;
            this.label6.Text = "Город:";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label5.ForeColor = System.Drawing.Color.Navy;
            this.label5.Location = new System.Drawing.Point(51, 82);
            this.label5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(58, 16);
            this.label5.TabIndex = 27;
            this.label5.Text = "Район:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label2.ForeColor = System.Drawing.Color.Navy;
            this.label2.Location = new System.Drawing.Point(8, 22);
            this.label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(104, 16);
            this.label2.TabIndex = 26;
            this.label2.Text = "Код региона:";
            // 
            // _kvartTb
            // 
            this._kvartTb.Location = new System.Drawing.Point(416, 318);
            this._kvartTb.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._kvartTb.Name = "_kvartTb";
            this._kvartTb.Size = new System.Drawing.Size(65, 25);
            this._kvartTb.TabIndex = 9;
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label11.ForeColor = System.Drawing.Color.Navy;
            this.label11.Location = new System.Drawing.Point(331, 324);
            this.label11.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(83, 16);
            this.label11.TabIndex = 24;
            this.label11.Text = "Квартира:";
            // 
            // _korpTb
            // 
            this._korpTb.Location = new System.Drawing.Point(256, 319);
            this._korpTb.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._korpTb.Name = "_korpTb";
            this._korpTb.Size = new System.Drawing.Size(65, 25);
            this._korpTb.TabIndex = 8;
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label10.ForeColor = System.Drawing.Color.Navy;
            this.label10.Location = new System.Drawing.Point(187, 324);
            this.label10.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(65, 16);
            this.label10.TabIndex = 22;
            this.label10.Text = "Корпус:";
            // 
            // _domTb
            // 
            this._domTb.Location = new System.Drawing.Point(112, 319);
            this._domTb.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._domTb.Name = "_domTb";
            this._domTb.Size = new System.Drawing.Size(65, 25);
            this._domTb.TabIndex = 7;
            // 
            // _ulicaSelectBtn
            // 
            this._ulicaSelectBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("_ulicaSelectBtn.BackgroundImage")));
            this._ulicaSelectBtn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this._ulicaSelectBtn.Font = new System.Drawing.Font("Trebuchet MS", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this._ulicaSelectBtn.Location = new System.Drawing.Point(615, 259);
            this._ulicaSelectBtn.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._ulicaSelectBtn.Name = "_ulicaSelectBtn";
            this._ulicaSelectBtn.Size = new System.Drawing.Size(25, 25);
            this._ulicaSelectBtn.TabIndex = 19;
            this._ulicaSelectBtn.Text = ">>";
            this._ulicaSelectBtn.UseVisualStyleBackColor = true;
            this._ulicaSelectBtn.Visible = false;
            // 
            // _ulicaTb
            // 
            this._ulicaTb.Location = new System.Drawing.Point(113, 258);
            this._ulicaTb.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._ulicaTb.Name = "_ulicaTb";
            this._ulicaTb.Size = new System.Drawing.Size(465, 25);
            this._ulicaTb.TabIndex = 6;
            this._ulicaTb.TextChanged += new System.EventHandler(this._textChanged);
            this._ulicaTb.KeyDown += new System.Windows.Forms.KeyEventHandler(this._kodRegTb_KeyDown);
            this._ulicaTb.Leave += new System.EventHandler(this._onTextBoxLeave);
            this._ulicaTb.Enter += new System.EventHandler(this._onTextBoxItemEnter);
            // 
            // _naspunktSelectBtn
            // 
            this._naspunktSelectBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("_naspunktSelectBtn.BackgroundImage")));
            this._naspunktSelectBtn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this._naspunktSelectBtn.Font = new System.Drawing.Font("Trebuchet MS", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this._naspunktSelectBtn.Location = new System.Drawing.Point(614, 198);
            this._naspunktSelectBtn.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._naspunktSelectBtn.Name = "_naspunktSelectBtn";
            this._naspunktSelectBtn.Size = new System.Drawing.Size(25, 25);
            this._naspunktSelectBtn.TabIndex = 16;
            this._naspunktSelectBtn.Text = ">>";
            this._naspunktSelectBtn.UseVisualStyleBackColor = true;
            this._naspunktSelectBtn.Visible = false;
            // 
            // _naspunktTb
            // 
            this._naspunktTb.Location = new System.Drawing.Point(112, 198);
            this._naspunktTb.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._naspunktTb.Name = "_naspunktTb";
            this._naspunktTb.Size = new System.Drawing.Size(465, 25);
            this._naspunktTb.TabIndex = 5;
            this._naspunktTb.TextChanged += new System.EventHandler(this._textChanged);
            this._naspunktTb.KeyDown += new System.Windows.Forms.KeyEventHandler(this._kodRegTb_KeyDown);
            this._naspunktTb.Leave += new System.EventHandler(this._onTextBoxLeave);
            this._naspunktTb.Enter += new System.EventHandler(this._onTextBoxItemEnter);
            // 
            // _gorodSelectBtn
            // 
            this._gorodSelectBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("_gorodSelectBtn.BackgroundImage")));
            this._gorodSelectBtn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this._gorodSelectBtn.Font = new System.Drawing.Font("Trebuchet MS", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this._gorodSelectBtn.Location = new System.Drawing.Point(614, 139);
            this._gorodSelectBtn.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._gorodSelectBtn.Name = "_gorodSelectBtn";
            this._gorodSelectBtn.Size = new System.Drawing.Size(25, 25);
            this._gorodSelectBtn.TabIndex = 13;
            this._gorodSelectBtn.Text = ">>";
            this._gorodSelectBtn.UseVisualStyleBackColor = true;
            this._gorodSelectBtn.Visible = false;
            // 
            // _gorodTb
            // 
            this._gorodTb.Location = new System.Drawing.Point(112, 138);
            this._gorodTb.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._gorodTb.Name = "_gorodTb";
            this._gorodTb.Size = new System.Drawing.Size(465, 25);
            this._gorodTb.TabIndex = 4;
            this._gorodTb.TextChanged += new System.EventHandler(this._textChanged);
            this._gorodTb.KeyDown += new System.Windows.Forms.KeyEventHandler(this._kodRegTb_KeyDown);
            this._gorodTb.Leave += new System.EventHandler(this._onTextBoxLeave);
            this._gorodTb.Enter += new System.EventHandler(this._onTextBoxItemEnter);
            // 
            // _raionSelectBtn
            // 
            this._raionSelectBtn.BackColor = System.Drawing.Color.White;
            this._raionSelectBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("_raionSelectBtn.BackgroundImage")));
            this._raionSelectBtn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this._raionSelectBtn.Font = new System.Drawing.Font("Trebuchet MS", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this._raionSelectBtn.Location = new System.Drawing.Point(615, 78);
            this._raionSelectBtn.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._raionSelectBtn.Name = "_raionSelectBtn";
            this._raionSelectBtn.Size = new System.Drawing.Size(25, 25);
            this._raionSelectBtn.TabIndex = 10;
            this._raionSelectBtn.UseVisualStyleBackColor = false;
            this._raionSelectBtn.Visible = false;
            // 
            // _raionTb
            // 
            this._raionTb.Location = new System.Drawing.Point(113, 77);
            this._raionTb.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._raionTb.Name = "_raionTb";
            this._raionTb.Size = new System.Drawing.Size(465, 25);
            this._raionTb.TabIndex = 3;
            this._raionTb.TextChanged += new System.EventHandler(this._textChanged);
            this._raionTb.PreviewKeyDown += new System.Windows.Forms.PreviewKeyDownEventHandler(this._raionTb_PreviewKeyDown);
            this._raionTb.KeyDown += new System.Windows.Forms.KeyEventHandler(this._kodRegTb_KeyDown);
            this._raionTb.Leave += new System.EventHandler(this._onTextBoxLeave);
            this._raionTb.Enter += new System.EventHandler(this._onTextBoxItemEnter);
            // 
            // _indexTb
            // 
            this._indexTb.Location = new System.Drawing.Point(513, 17);
            this._indexTb.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._indexTb.Name = "_indexTb";
            this._indexTb.Size = new System.Drawing.Size(65, 25);
            this._indexTb.TabIndex = 2;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label4.ForeColor = System.Drawing.Color.Navy;
            this.label4.Location = new System.Drawing.Point(441, 22);
            this.label4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(66, 16);
            this.label4.TabIndex = 6;
            this.label4.Text = "Индекс:";
            // 
            // _regLabel
            // 
            this._regLabel.AutoSize = true;
            this._regLabel.Location = new System.Drawing.Point(219, 20);
            this._regLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this._regLabel.Name = "_regLabel";
            this._regLabel.Size = new System.Drawing.Size(118, 20);
            this._regLabel.TabIndex = 5;
            this._regLabel.Text = "Метка региона:";
            // 
            // _kodRegBtn
            // 
            this._kodRegBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("_kodRegBtn.BackgroundImage")));
            this._kodRegBtn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this._kodRegBtn.Font = new System.Drawing.Font("Trebuchet MS", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this._kodRegBtn.Location = new System.Drawing.Point(186, 17);
            this._kodRegBtn.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._kodRegBtn.Name = "_kodRegBtn";
            this._kodRegBtn.Size = new System.Drawing.Size(25, 25);
            this._kodRegBtn.TabIndex = 4;
            this._kodRegBtn.UseVisualStyleBackColor = true;
            this._kodRegBtn.Visible = false;
            // 
            // _kodRegTb
            // 
            this._kodRegTb.AcceptsTab = true;
            this._kodRegTb.Location = new System.Drawing.Point(113, 17);
            this._kodRegTb.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._kodRegTb.Name = "_kodRegTb";
            this._kodRegTb.Size = new System.Drawing.Size(65, 25);
            this._kodRegTb.TabIndex = 1;
            this._kodRegTb.TextChanged += new System.EventHandler(this._textChanged);
            this._kodRegTb.PreviewKeyDown += new System.Windows.Forms.PreviewKeyDownEventHandler(this._onTextBox_PreviewKeyDown);
            this._kodRegTb.KeyDown += new System.Windows.Forms.KeyEventHandler(this._kodRegTb_KeyDown);
            this._kodRegTb.Leave += new System.EventHandler(this._onTextBoxLeave);
            this._kodRegTb.Enter += new System.EventHandler(this._onTextBoxItemEnter);
            // 
            // _fullAddrTb
            // 
            this._fullAddrTb.BackColor = System.Drawing.Color.WhiteSmoke;
            this._fullAddrTb.Location = new System.Drawing.Point(117, 12);
            this._fullAddrTb.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._fullAddrTb.Multiline = true;
            this._fullAddrTb.Name = "_fullAddrTb";
            this._fullAddrTb.ReadOnly = true;
            this._fullAddrTb.Size = new System.Drawing.Size(528, 55);
            this._fullAddrTb.TabIndex = 33;
            this._fullAddrTb.TabStop = false;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label1.ForeColor = System.Drawing.Color.Navy;
            this.label1.Location = new System.Drawing.Point(31, 16);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(82, 32);
            this.label1.TabIndex = 30;
            this.label1.Text = "Адрес \r\nисходный:";
            // 
            // _rightWorkspace
            // 
            this._rightWorkspace.Location = new System.Drawing.Point(652, 12);
            this._rightWorkspace.Name = "_rightWorkspace";
            this._rightWorkspace.Size = new System.Drawing.Size(369, 440);
            this._rightWorkspace.TabIndex = 10;
            this._rightWorkspace.Text = "_rightWorkspace";
            // 
            // _termianteBtn
            // 
            this._termianteBtn.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this._termianteBtn.Image = ((System.Drawing.Image)(resources.GetObject("_termianteBtn.Image")));
            this._termianteBtn.ImageTransparentColor = System.Drawing.Color.Magenta;
            this._termianteBtn.Name = "_termianteBtn";
            this._termianteBtn.Size = new System.Drawing.Size(163, 22);
            this._termianteBtn.Text = "Прервать контроль";
            this._termianteBtn.Click += new System.EventHandler(this._termianteBtn_Click);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(6, 25);
            // 
            // EditorView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.Controls.Add(this._rightWorkspace);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this._fullAddrTb);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.toolStrip1);
            this.Font = new System.Drawing.Font("Trebuchet MS", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Name = "EditorView";
            this.Size = new System.Drawing.Size(1024, 482);
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this._UlicaErrorPicture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._NaspunktErrorPicture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._GorodErrorPicture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._RaionErrorPicture)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.ToolStripButton _saveAndCloseBtn;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripButton _closeBtn;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.PictureBox _UlicaErrorPicture;
        private System.Windows.Forms.PictureBox _NaspunktErrorPicture;
        private System.Windows.Forms.PictureBox _GorodErrorPicture;
        private System.Windows.Forms.PictureBox _RaionErrorPicture;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox _kvartTb;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.TextBox _korpTb;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.TextBox _domTb;
        private System.Windows.Forms.Button _ulicaSelectBtn;
        private System.Windows.Forms.TextBox _ulicaTb;
        private System.Windows.Forms.Button _naspunktSelectBtn;
        private System.Windows.Forms.TextBox _naspunktTb;
        private System.Windows.Forms.Button _gorodSelectBtn;
        private System.Windows.Forms.TextBox _gorodTb;
        private System.Windows.Forms.Button _raionSelectBtn;
        private System.Windows.Forms.TextBox _raionTb;
        private System.Windows.Forms.TextBox _indexTb;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label _regLabel;
        private System.Windows.Forms.Button _kodRegBtn;
        private System.Windows.Forms.TextBox _kodRegTb;
        private System.Windows.Forms.TextBox _fullAddrTb;
        private System.Windows.Forms.Label label1;
        private Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace _rightWorkspace;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.ToolStripButton _termianteBtn;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;




    }
}

